---
version: 2.1
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - crystal/test
  build_and_test:
    jobs:
      - crystal/test
orbs:
  crystal: manastech/crystal@1.0
