---
version: 2.1
workflows:
   version: 2
   build_and_test:
     triggers:
       - schedule:
           cron: "0 0 * * 0"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
jobs:
  build:
    working_directory: ~/crystal-binary_parser
    docker:
      - image: crystallang/crystal
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "shard.yml" }}
      - run:
          name: Install depencies
          command: shards
      - save_cache:
          key: dependency-cache-{{ checksum "shard.yml" }}
          paths:
            - ./lib
      - run:
          name: Test
          command: crystal spec
