version: 2
workflows:
   version: 2
   build:
     triggers:
       - schedule:
           cron: "0 0 * * 0"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test
jobs:
  test:
    working_directory: ~/crystal-binary_parser
    docker:
      - image: crystallang/crystal
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "shard.yml" }}
      - run:
          name: Install depencies
          command: shards
      - save_cache:
          key: dependency-cache-{{ checksum "shard.yml" }}
          paths:
            - ./lib
      - run:
          name: Test
          command: crystal spec
